# Generated by Django 3.2.16 on 2023-03-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socadmin', '0002_auto_20230314_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='answer',
            field=models.CharField(default='Blaze Galaxy', max_length=255),
            preserve_default=False,
        ),
    ]
